### ISSUE TITLE
Checkov integration

### ISSUE THREAD

**Issue by schosterbarak** [rdkls/tf-parliament#1]
Hey @rdkls, 
I'd like to integrate this solution with https://github.com/bridgecrewio/checkov
I've done most of it and would like to mention you as a contributor since i relied heavily on your code.
would that be ok?
would you like me to send you the code and have the contribution under your name?

**Comment by rdkls** [comment]
Hi @schosterbarak sorry for missing your Q - yes I'd love to see it getting some use, please go ahead
per another issue I'll add a license ....
